<a href="https://colab.research.google.com/github/Sagar25-prac/DA-with-Numpy-and-Pandas/blob/main/Numpy_by_intellipat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

Numpy is better than list:


*   Its faster.
*   Its memory efficient.
*   We dont need to do manual loop it is direct vectorized.
*   Numpy has powerful Built in functions.






In [ ]:
import numpy as np

In [ ]:
# Creating an Array

np.array([1,2,3,4])

array([1, 2, 3, 4])

32 ------ Scalar
[1,2,3] ---- 1 dimension
[[1,2,3,4],[5,6,7]] --- 2 dimension





In [ ]:
#dimension

arr = np.array([1,2,3,4,5])
print(arr.ndim)
print(arr.shape)

1
(5,)


In [ ]:
a = np.array([])
print(a.ndim)
print(a.shape)

1
(0,)


In [ ]:
# Create a range of the array

range = np.arange(1,10,1) #start,stop,step last value is excluded
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.linspace(0,1,5) # start,stop,number of values between them
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
log = np.logspace(1,3,3) # logarithmic scale array ->10^1,10^2,10^3 start point on the power end point on the power and step in value for even distribution
log

array([  10.,  100., 1000.])

In [ ]:
zeros = np.zeros(5)
print(zeros)

zeros_matrix = np.zeros([2,3])
print(zeros_matrix)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones = np.ones(2,dtype=int)
print(ones)

ones_matrix = np.ones([2,3])
print(ones_matrix)

[1 1]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# To print single value
sig = np.full(3,2)
print(sig)

sig2d = np.full([2,3],4)
print(sig2d)

[2 2 2]
[[4 4 4]
 [4 4 4]]


In [ ]:
# uninitialized array to craete an empty array
emp = np.empty([2,3])
emp

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.random.rand(10)  # random floats

array([0.15736689, 0.91137332, 0.32808614, 0.03444567, 0.86014762,
       0.06810232, 0.00112512, 0.10991517, 0.67485044, 0.27703797])

In [ ]:
np.random.rand(2,3)

array([[0.68097016, 0.60410106, 0.27265854],
       [0.86831487, 0.62828022, 0.77596421]])

In [ ]:
np.random.randn(2,3) # random floats from standard normal deviation

array([[-0.58588206, -0.62272397, -2.2655988 ],
       [ 0.52681164,  1.56275164, -1.87109774]])

In [ ]:
a = np.random.randint(10,100) # random integers  start,stop and dimension i.e no. of values
print(a)

b = np.random.randint(10,100,[2,4])
print(b)

52
[[83 69 65 54]
 [52 59 51 60]]


**Numpy Data Types and Type Casting**

In [ ]:
a = np.array([1,2.0,3,4,5])
a

array([1., 2., 3., 4., 5.])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
lst = [1,'sagar',5.5]
arr = np.array(lst)
arr

array(['1', 'sagar', '5.5'], dtype='<U32')

In [ ]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [ ]:
con = np.array([1,2,3,4],dtype=np.float64)
print(con)
print(con.dtype)

conit = np.array([1,2.2,3],dtype=np.int64)
print(conit)
print(conit.dtype)




[1. 2. 3. 4.]
float64
[1 2 3]
int64


In [ ]:
#type casting is to convert datatype using astype()

In [ ]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [ ]:
new_arr = arr.astype(np.float64)
new_arr.dtype

dtype('float64')

In [ ]:
# create multidimensional array

m = np.array([[1,2,3],
             [2,3,4]])

In [ ]:
print(m.ndim) # no. of dimension
print(m.shape) #no. of rows and columns
print(m.size) # no. of elements

2
(2, 3)
6


In [ ]:
m.itemsize # each elements taking how many bytes of memory

8

**Array Reshaping -> Reshape,Ravel and flatten**

In [ ]:
# Reshape

arr = np.array([1,2,3,4,5,6])
print(arr)

reshape = arr.reshape(2,3)
print(reshape)

reshaped = reshape.reshape(3,2)
print(reshaped)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Ravel -> used to covert into 1D array create a view
ravel = reshaped.ravel()
print(ravel)
print(reshaped)


[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# flatten -> used to convert into 1D array but create a copy

flat = reshaped.flatten()
print(flat)
print(reshaped)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


**Arithmetic Operation on Arrays**

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
#addition
print(a+b)

#Substraction
print(b-a)

#Multiplication
print(a*b)

#Division
print(b/a)

#int division
print(b//a)

# Remainder/Modulus
print(b%a)

#power/exponential
print(b**a)



[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
[4 2 2]
[0 1 0]
[  4  25 216]


**Universal Functions**

In [ ]:
#square root
uf = np.array([1,4,9,16,21])
sqrt = np.sqrt(uf)
sqrt

array([1.        , 2.        , 3.        , 4.        , 4.58257569])

In [ ]:
# Exponential
exp = np.exp(uf)
exp

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       1.31881573e+09])

In [ ]:
#sin function

angles = np.array([0,np.pi/2,np.pi])
sine_values = np.sin(angles)
print(sine_values)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


**Aggregate Functions**

In [ ]:
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))

6
1
3
2.0
2.0
0.816496580927726
0.6666666666666666


In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(matrix,axis=0)

array([12, 15, 18])

In [ ]:
np.sum(matrix,axis=1)

array([ 6, 15, 24])

In [ ]:
# Cummulative sum

print(np.cumsum(a))


print(np.cumprod(a))

[1 3 6]
[1 2 6]


**Slicing and Indexing**

In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
a[0:3]

array([1, 2, 3])

In [ ]:
a[::2]

array([1, 3, 5])

In [ ]:
print(a[-1])

6


In [ ]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(matrix[0:3:2])

[[1 2 3]
 [7 8 9]]


In [ ]:
# Index Arrsys -> Advance Indexing

a = np.array([1,2,3,4,5,6])
b= [0,4]
print(np.take( a,b ))

[1 5]


**Transpose**

In [ ]:
mat = np.array([[1,2,3],[4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x = mat.transpose()
x

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# Swapaxes -> swap 2 specific axes in a matrix
print(x.shape)
print(np.shape(np.swapaxes(mat,0,1)))

(3, 2)
(3, 2)


In [ ]:
np.swapaxes(x,1,1)


array([[1, 4],
       [2, 5],
       [3, 6]])

**Concat**

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
combine = np.concatenate([a,b])
combine

array([1, 2, 3, 4, 5, 6])

In [ ]:
ostack = np.stack([a,b],axis= 0)
print(ostack)

lstack = np.stack([a,b],axis= 1)
print(lstack)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
vstack = np.vstack([a,b])
vstack

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
hstack = np.hstack([a,b])
hstack

array([1, 2, 3, 4, 5, 6])

In [ ]:
split = np.split(combine,2)
split

[array([1, 2, 3]), array([4, 5, 6])]

In [ ]:
hsplit = np.hsplit(combine,2)
hsplit

[array([1, 2, 3]), array([4, 5, 6])]

In [ ]:
vsplit = np.hsplit(lstack,1)
vsplit

[array([[1, 4],
        [2, 5],
        [3, 6]])]

**Repeat and Tile**

In [ ]:
print(np.repeat(a,2)) # Repeat each element

[1 1 2 2 3 3]


In [ ]:
print(np.tile(a,2))  # Repeat entire array

[1 2 3 1 2 3]


In [ ]:
#Condition

a

array([1, 2, 3])

In [ ]:
np.where(a>1,'high','low')

array(['low', 'high', 'high'], dtype='<U4')

In [ ]:
np.argwhere(a<3)

array([[0],
       [1]])

**Logical And**

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
mask = np.logical_and(arr>3,arr<9)
mask

array([False, False, False,  True,  True,  True,  True,  True, False])

In [ ]:
arr[mask]

array([4, 5, 6, 7, 8])

In [ ]:
mark1 = np.logical_or(arr>4,arr<2)
mark1

array([ True, False, False, False,  True,  True,  True,  True,  True])

In [ ]:
arr[mark1]

array([1, 5, 6, 7, 8, 9])

In [ ]:
arr2 = np.array([0,1,5,0,5])

In [ ]:
n=np.nonzero(arr2)
n

(array([1, 2, 4]),)

In [ ]:
arr2[n]

array([1, 5, 5])

**Broadcasting**

Numpy always compare the shape of the arrays from the end (right to left).



*  If shapes are equal, They're compatible.
*  If one is 1,It can be streched to match the other.
*  If shapes are different and not 1 or equal --> X Error.





In [ ]:
image = np.array([[100,200],[300,400]])
image

array([[100, 200],
       [300, 400]])

In [ ]:
brightness =  image + 50
brightness

array([[150, 250],
       [350, 450]])

**Vectorization**

np.vector() -> convert a regular function to be applied on an array

In [ ]:
def square(x):
  return x*x

vfunc = np.vectorize(square)


In [ ]:
arr = np.array([1,2,3])

In [ ]:
vfunc(arr)

array([1, 4, 9])