<a href="https://colab.research.google.com/github/Sagar25-prac/DA-with-Numpy-and-Pandas/blob/main/Numpy_By_patrick.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.__version__)

2.0.2


In [4]:
a = np.array([1,2,3,4])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)

[1 2 3 4]
(4,)
int64
1
4
8


In [6]:
print(a[0])
print(a[3])

1
4


In [7]:
a[0] = 10

In [8]:
print(a)

[10  2  3  4]


In [10]:
b = a*np.array([2,3,4,5])
print(b)

[20  6 12 20]


In [12]:
b = a+ [4]
print(b)

[14  6  7  8]


In [16]:
# dot product

# using list

l1 = [1,2,3]
l2 = [4,5,6]

dot = 0

for i in range(len(l1)):
    dot += l1[i]*l2[i]

print(dot)

# using numpy
a1 = np.array(l1)
a2 = np.array(l2)
dot = np.dot(l1,l2)
print(dot)

32
32


In [18]:
pro = a1*a2

print(pro)

[ 4 10 18]


In [20]:
dot = sum(pro)
print(dot)

32


In [21]:
dot = a1 @ a2
print(dot)

32


In [23]:
m1 = np.array([[1,2,3],[4,5,6]])
print(m1)
print(m1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [24]:
print(m1[1,1])

5


In [26]:
print(m1[0,:])

[1 2 3]


In [27]:
print(m1[:,0])

[1 4]


In [29]:
print(np.transpose(m1))

[[1 4]
 [2 5]
 [3 6]]


In [32]:
m2 = np.array([[1,2],[3,4]])

print(np.linalg.inv(m2)) # invert of an array

[[-2.   1. ]
 [ 1.5 -0.5]]


In [33]:
print(np.linalg.det(m2)) # determinent of an array

-2.0000000000000004


In [35]:
print(np.diag(m2)) # diagnal of the array

[1 4]


In [40]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

bol_idx = a>2
print(bol_idx)

# Corrected line: Use the boolean mask 'bol_idx' to select elements from 'a'
print(a[bol_idx])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [41]:
# we can do it simple

print(a[a>2])

[3 4 5 6]


In [42]:
b = np.where(a>2,a,'NAN')
print(b)

[['NAN' 'NAN']
 ['3' '4']
 ['5' '6']]


In [43]:
# fancy indexing

a = np.array([10,11,12,13,14,15,16,17,18,19])
print(a)
b= [1,2,5]
print(a[b])

[10 11 12 13 14 15 16 17 18 19]
[11 12 15]


In [45]:
# print only even array

even = np.argwhere(a%2==0).flatten()
print(a[even])

[10 12 14 16 18]


In [46]:
res = np.arange(1,7)
print(res)
print(res.shape)

res1 = res.reshape(2,3)
print(res1)
print(res1.shape)


[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [47]:
a = np.array([[1,1],[1.5,4]])
b= np.array([2200,5050])


In [52]:
c= np.linalg.inv(a).dot(b)

In [53]:
print(c)

[1500.  700.]


In [54]:
x = np.linalg.solve(a,b)
print(x)

[1500.  700.]
